name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-mix-
    - uses: actions/cache@v1
      with:
        path: priv/plts
        key: ${{ runner.os }}-plts
        resore-keys: ${{ runner.os }}-plts
    - name: Install Dependencies
      run: |
        mkdir -p priv/plts
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: MIX_ENV=test mix quality.ci
